name: Go Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v3
  
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Install dependencies
      run: go get .

    - name: Run tests
      run: make test_all

